"""add synthetic kennel domain

Revision ID: 0cc49c993626
Revises:
Create Date: 2026-09-17 13:03:26.878443
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0cc49c993626"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.create_table(
        "demo_datasets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("semantic_checksum", sa.String(length=64), nullable=True),
        sa.Column(
            "seeded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "dogs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("sex", sa.String(length=16), nullable=False),
        sa.Column("is_neutered", sa.Boolean(), nullable=False),
        sa.Column("neutered_on", sa.Date(), nullable=True),
        sa.Column("litter_id", sa.Integer(), nullable=True),
        sa.Column("photo_key", sa.String(length=255), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint("sex IN ('female', 'male')", name="ck_dogs_sex"),
        sa.CheckConstraint(
            "neutered_on IS NULL OR neutered_on >= birth_date",
            name="ck_dogs_neutered_after_birth",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("public_id"),
    )
    op.create_index(op.f("ix_dogs_birth_date"), "dogs", ["birth_date"], unique=False)
    op.create_index(
        "uq_dogs_name_lower", "dogs", [sa.literal_column("lower(name)")], unique=True
    )
    op.create_table(
        "litters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=1), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("mother_id", sa.Integer(), nullable=True),
        sa.Column("father_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "char_length(code) = 1", name="ck_litters_single_letter_code"
        ),
        sa.CheckConstraint(
            "mother_id IS NULL OR father_id IS NULL OR mother_id <> father_id",
            name="ck_litters_distinct_parents",
        ),
        sa.ForeignKeyConstraint(["father_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["mother_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_litters_birth_date"), "litters", ["birth_date"], unique=False
    )
    op.create_index(
        op.f("ix_litters_father_id"), "litters", ["father_id"], unique=False
    )
    op.create_index(
        op.f("ix_litters_mother_id"), "litters", ["mother_id"], unique=False
    )
    op.create_foreign_key(
        "fk_dogs_litter_id",
        "dogs",
        "litters",
        ["litter_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_table(
        "kennel_locations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("location_type", sa.String(length=30), nullable=False),
        sa.Column("zone", sa.String(length=30), nullable=False),
        sa.Column("row_label", sa.String(length=30), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "location_type IN ('adult_enclosure', 'puppy_area')",
            name="ck_kennel_locations_type",
        ),
        sa.CheckConstraint(
            "capacity > 0", name="ck_kennel_locations_positive_capacity"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint(
            "zone", "row_label", "position", name="uq_location_map_position"
        ),
    )
    op.create_index(
        op.f("ix_kennel_locations_location_type"),
        "kennel_locations",
        ["location_type"],
        unique=False,
    )
    op.create_table(
        "work_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_reference", sa.String(length=80), nullable=False),
        sa.Column("work_date", sa.Date(), nullable=False),
        sa.Column("distance_km", sa.SmallInteger(), nullable=False),
        sa.Column("activity_type", sa.String(length=30), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=True),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "activity_type = 'sled_training'", name="ck_work_sessions_activity_type"
        ),
        sa.CheckConstraint(
            "distance_km IN (5, 10)", name="ck_work_sessions_canonical_distance"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_reference"),
    )
    op.create_index(
        op.f("ix_work_sessions_work_date"), "work_sessions", ["work_date"], unique=False
    )
    op.create_index(
        "ix_work_sessions_work_date_distance",
        "work_sessions",
        ["work_date", "distance_km"],
        unique=False,
    )
    op.create_table(
        "dog_archives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("archive_date", sa.Date(), nullable=False),
        sa.Column("reason", sa.String(length=40), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "reason IN ('euthanized', 'deceased', 'rehomed_to_guide')",
            name="ck_dog_archives_reason",
        ),
        sa.ForeignKeyConstraint(["dog_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dog_archives_archive_date"),
        "dog_archives",
        ["archive_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dog_archives_dog_id"), "dog_archives", ["dog_id"], unique=True
    )
    op.create_table(
        "dog_availability_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("availability_state", sa.String(length=20), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "valid_range",
            postgresql.DATERANGE(),
            sa.Computed(
                "daterange(valid_from, COALESCE(valid_to, '9999-12-31'::date), '[)')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=255), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("dog_id"), "="),
            (sa.column("valid_range"), "&&"),
            using="gist",
            name="excl_dog_availability_periods_overlap",
        ),
        sa.CheckConstraint(
            "availability_state IN "
            "('available', 'injured', 'rest', 'restricted', 'retired')",
            name="ck_dog_availability_periods_state",
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name="ck_availability_valid_range",
        ),
        sa.ForeignKeyConstraint(["dog_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dog_availability_periods_dog_id"),
        "dog_availability_periods",
        ["dog_id"],
        unique=False,
    )
    op.create_table(
        "dog_class_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("dog_class", sa.String(length=20), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "valid_range",
            postgresql.DATERANGE(),
            sa.Computed(
                "daterange(valid_from, COALESCE(valid_to, '9999-12-31'::date), '[)')",
                persisted=True,
            ),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("dog_id"), "="),
            (sa.column("valid_range"), "&&"),
            using="gist",
            name="excl_dog_class_periods_overlap",
        ),
        sa.CheckConstraint(
            "dog_class IN ('puppy', 'junior', 'training', 'standard')",
            name="ck_dog_class_periods_class",
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="ck_class_valid_range"
        ),
        sa.ForeignKeyConstraint(["dog_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dog_class_periods_dog_id"),
        "dog_class_periods",
        ["dog_id"],
        unique=False,
    )
    op.create_table(
        "dog_lifecycle_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("lifecycle_state", sa.String(length=20), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "valid_range",
            postgresql.DATERANGE(),
            sa.Computed(
                "daterange(valid_from, COALESCE(valid_to, '9999-12-31'::date), '[)')",
                persisted=True,
            ),
            nullable=False,
        ),
        postgresql.ExcludeConstraint(
            (sa.column("dog_id"), "="),
            (sa.column("valid_range"), "&&"),
            using="gist",
            name="excl_dog_lifecycle_periods_overlap",
        ),
        sa.CheckConstraint(
            "lifecycle_state IN ('active', 'archived')",
            name="ck_dog_lifecycle_periods_state",
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="ck_lifecycle_valid_range"
        ),
        sa.ForeignKeyConstraint(["dog_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dog_lifecycle_periods_dog_id"),
        "dog_lifecycle_periods",
        ["dog_id"],
        unique=False,
    )
    op.create_table(
        "dog_relationship_constraints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dog_a_id", sa.Integer(), nullable=False),
        sa.Column("dog_b_id", sa.Integer(), nullable=False),
        sa.Column("relationship_kind", sa.String(length=30), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "relationship_kind IN ('preferred_pair', 'hard_conflict')",
            name="ck_relationship_kind",
        ),
        sa.CheckConstraint(
            "dog_a_id < dog_b_id", name="ck_relationship_canonical_pair_order"
        ),
        sa.ForeignKeyConstraint(["dog_a_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["dog_b_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dog_a_id",
            "dog_b_id",
            "relationship_kind",
            name="uq_relationship_pair_kind",
        ),
    )
    op.create_index(
        op.f("ix_dog_relationship_constraints_dog_a_id"),
        "dog_relationship_constraints",
        ["dog_a_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dog_relationship_constraints_dog_b_id"),
        "dog_relationship_constraints",
        ["dog_b_id"],
        unique=False,
    )
    op.create_table(
        "dog_role_capabilities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "role IN ('lead', 'team', 'wheel')", name="ck_role_capabilities_role"
        ),
        sa.ForeignKeyConstraint(["dog_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dog_id", "role", name="uq_dog_role_capability"),
    )
    op.create_index(
        op.f("ix_dog_role_capabilities_dog_id"),
        "dog_role_capabilities",
        ["dog_id"],
        unique=False,
    )
    op.create_table(
        "housing_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column(
            "valid_range",
            postgresql.DATERANGE(),
            sa.Computed(
                "daterange(valid_from, COALESCE(valid_to, '9999-12-31'::date), '[)')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=255), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("dog_id"), "="),
            (sa.column("valid_range"), "&&"),
            using="gist",
            name="excl_housing_assignments_dog_overlap",
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name="ck_housing_valid_range"
        ),
        sa.ForeignKeyConstraint(["dog_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["location_id"], ["kennel_locations.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_housing_assignments_dog_id"),
        "housing_assignments",
        ["dog_id"],
        unique=False,
    )
    op.create_index(
        "ix_housing_assignments_location_dates",
        "housing_assignments",
        ["location_id", "valid_from", "valid_to"],
        unique=False,
    )
    op.create_index(
        op.f("ix_housing_assignments_location_id"),
        "housing_assignments",
        ["location_id"],
        unique=False,
    )
    op.create_table(
        "work_participations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("dog_id", sa.Integer(), nullable=False),
        sa.Column("assigned_role", sa.String(length=20), nullable=True),
        sa.CheckConstraint(
            "assigned_role IS NULL OR assigned_role IN ('lead', 'team', 'wheel')",
            name="ck_work_participations_role",
        ),
        sa.ForeignKeyConstraint(["dog_id"], ["dogs.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["session_id"], ["work_sessions.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "dog_id", name="uq_work_participation_start"),
    )
    op.create_index(
        op.f("ix_work_participations_dog_id"),
        "work_participations",
        ["dog_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_work_participations_session_id"),
        "work_participations",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_participations_session_id"), table_name="work_participations"
    )
    op.drop_index(
        op.f("ix_work_participations_dog_id"), table_name="work_participations"
    )
    op.drop_table("work_participations")
    op.drop_constraint("fk_dogs_litter_id", "dogs", type_="foreignkey")
    op.drop_index(op.f("ix_litters_mother_id"), table_name="litters")
    op.drop_index(op.f("ix_litters_father_id"), table_name="litters")
    op.drop_index(op.f("ix_litters_birth_date"), table_name="litters")
    op.drop_table("litters")
    op.drop_index(
        op.f("ix_housing_assignments_location_id"), table_name="housing_assignments"
    )
    op.drop_index(
        "ix_housing_assignments_location_dates", table_name="housing_assignments"
    )
    op.drop_index(
        op.f("ix_housing_assignments_dog_id"), table_name="housing_assignments"
    )
    op.drop_table("housing_assignments")
    op.drop_index(
        op.f("ix_dog_role_capabilities_dog_id"), table_name="dog_role_capabilities"
    )
    op.drop_table("dog_role_capabilities")
    op.drop_index(
        op.f("ix_dog_relationship_constraints_dog_b_id"),
        table_name="dog_relationship_constraints",
    )
    op.drop_index(
        op.f("ix_dog_relationship_constraints_dog_a_id"),
        table_name="dog_relationship_constraints",
    )
    op.drop_table("dog_relationship_constraints")
    op.drop_index(
        op.f("ix_dog_lifecycle_periods_dog_id"), table_name="dog_lifecycle_periods"
    )
    op.drop_table("dog_lifecycle_periods")
    op.drop_index(op.f("ix_dog_class_periods_dog_id"), table_name="dog_class_periods")
    op.drop_table("dog_class_periods")
    op.drop_index(
        op.f("ix_dog_availability_periods_dog_id"),
        table_name="dog_availability_periods",
    )
    op.drop_table("dog_availability_periods")
    op.drop_index(op.f("ix_dog_archives_dog_id"), table_name="dog_archives")
    op.drop_index(op.f("ix_dog_archives_archive_date"), table_name="dog_archives")
    op.drop_table("dog_archives")
    op.drop_index("ix_work_sessions_work_date_distance", table_name="work_sessions")
    op.drop_index(op.f("ix_work_sessions_work_date"), table_name="work_sessions")
    op.drop_table("work_sessions")
    op.drop_index(
        op.f("ix_kennel_locations_location_type"), table_name="kennel_locations"
    )
    op.drop_table("kennel_locations")
    op.drop_index("uq_dogs_name_lower", table_name="dogs")
    op.drop_index(op.f("ix_dogs_birth_date"), table_name="dogs")
    op.drop_table("dogs")
    op.drop_table("demo_datasets")
    # ### end Alembic commands ###
