from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class VisualIdentity:
    coat_base: str
    coat_secondary: str
    facial_marking: str
    eye_color: str
    coat_length: str
    build: str
    ear_presentation: str
    tail_appearance: str
    approximate_visual_age: str
    distinctive_marking: str
    family_resemblance: str
    portrait_character: str


def _v(
    coat_base: str,
    coat_secondary: str,
    facial_marking: str,
    eye_color: str,
    coat_length: str,
    build: str,
    ear_presentation: str,
    tail_appearance: str,
    approximate_visual_age: str,
    distinctive_marking: str,
    family_resemblance: str,
    portrait_character: str,
) -> VisualIdentity:
    return VisualIdentity(
        coat_base,
        coat_secondary,
        facial_marking,
        eye_color,
        coat_length,
        build,
        ear_presentation,
        tail_appearance,
        approximate_visual_age,
        distinctive_marking,
        family_resemblance,
        portrait_character,
    )


# These identities are deliberately curated rather than randomly generated. Family
# cues recur through the represented pedigree, while every dog keeps a distinct face,
# palette, or marking for reliable visual recognition.
VISUAL_IDENTITIES: dict[str, VisualIdentity] = {
    "Aurora": _v(
        "silver grey",
        "clean white",
        "slim white blaze and soft grey mask",
        "warm amber",
        "medium dense",
        "lean mature",
        "upright with softly rounded tips",
        "full grey plume with white tip",
        "healthy senior adult with light muzzle silvering",
        "small silver spot above the right eye",
        "origin of the silver-grey Aurora line seen in C and H descendants",
        "calm square stance with an alert but gentle expression",
    ),
    "Atlas": _v(
        "deep black",
        "warm cream white",
        "broad cream blaze under a dark cap",
        "dark brown",
        "short dense",
        "broad-chested working",
        "high upright",
        "heavy black brush with cream underside",
        "healthy senior adult with a subtly greying chin",
        "narrow black bridge extending into the blaze",
        "dark-coated foundation line echoed in the D and K families",
        "steady three-quarter stance with head held confidently",
    ),
    "Freya": _v(
        "copper red",
        "ivory white",
        "open white face with red brow arcs",
        "golden amber",
        "medium plush",
        "athletic and balanced",
        "upright and close-set",
        "copper sickle tail with ivory tip",
        "mature adult with a faintly pale muzzle",
        "asymmetric ivory patch climbing the left cheek",
        "red-toned foundation line carried into the D and M families",
        "relaxed side-facing stance with attentive eyes",
    ),
    "Fjord": _v(
        "charcoal agouti",
        "smoky cream",
        "dark wolf mask with cream spectacles",
        "chestnut brown",
        "dense northern",
        "strong compact",
        "upright and slightly wide-set",
        "dense charcoal plume",
        "mature senior adult in robust condition",
        "cream crescent across the chest",
        "agouti foundation line recurring in H, N, and later descendants",
        "quiet planted stance with a seasoned working-dog presence",
    ),
    "Cedar": _v(
        "sable grey",
        "white",
        "narrow white blaze within a sable mask",
        "amber",
        "medium",
        "tall lean",
        "upright",
        "slender sable brush with white tip",
        "mature adult",
        "dark cedar-brown stripe along the spine",
        "Aurora's silver mask softened by the C-litter's sable external line",
        "alert forward stance with one forepaw slightly advanced",
    ),
    "Cinder": _v(
        "smoky charcoal",
        "silver white",
        "charcoal cap with a fine silver blaze",
        "brown",
        "short dense",
        "compact athletic",
        "upright with one tip subtly relaxed",
        "dark compact plume",
        "healthy young adult at the time represented",
        "pale flecking around the nose",
        "C-litter silver structure with the darkest external-sire expression",
        "natural side stance with a bright attentive look",
    ),
    "Cosmo": _v(
        "blue grey",
        "bright white",
        "wide white blaze and rounded grey eye patches",
        "one blue and one amber",
        "medium dense",
        "long-legged lean",
        "tall upright",
        "blue-grey plume with broad white tip",
        "mature adult",
        "small grey freckle on the white muzzle",
        "C-litter silver palette with Aurora's open expression",
        "curious three-quarter stance with ears fully forward",
    ),
    "Clover": _v(
        "soft wolf grey",
        "cream white",
        "cream heart-shaped forehead blaze",
        "hazel",
        "medium plush",
        "balanced athletic",
        "upright and slightly rounded",
        "soft grey curl with cream underside",
        "mature adult",
        "four small dark freckles on the muzzle",
        "C-litter grey face and Aurora's amber-family warmth",
        "friendly relaxed stance with a gentle head tilt",
    ),
    "Coast": _v(
        "pale silver",
        "snow white",
        "nearly open white face with silver temples",
        "ice blue",
        "medium",
        "rangy working",
        "upright and wide-set",
        "pale silver plume",
        "healthy mature adult at the time represented",
        "thin silver line beneath the left eye",
        "lightest C-litter expression and source of pale markings in the M line",
        "calm profile stance looking just past the camera",
    ),
    "Dune": _v(
        "sand red",
        "cream",
        "cream blaze split by a fine red center line",
        "amber brown",
        "short dense",
        "muscular athletic",
        "upright",
        "red brush with cream tip",
        "mature adult",
        "darker rust saddle over the shoulders",
        "Freya's copper palette combined with Atlas's broad frame",
        "grounded front three-quarter stance with a focused gaze",
    ),
    "Delta": _v(
        "dark copper",
        "white",
        "sharp white arrow blaze",
        "golden amber",
        "medium",
        "lean powerful",
        "high upright",
        "dark copper plume with white tip",
        "mature adult",
        "small white notch on the right ear edge",
        "D-litter red line with Atlas-like dark cap and structure",
        "poised side stance with an energetic attentive expression",
    ),
    "Django": _v(
        "black sable",
        "cream white",
        "cream goggles beneath a black forehead",
        "deep brown",
        "short dense",
        "broad athletic",
        "upright and close-set",
        "black brush with copper fringes",
        "healthy mature adult at the time represented",
        "single copper patch over the left shoulder",
        "D-litter dark Atlas expression with subtle Freya copper",
        "confident square stance in calm winter light",
    ),
    "Daisy": _v(
        "light copper",
        "ivory",
        "open ivory face with delicate copper eyebrows",
        "hazel green",
        "medium soft",
        "slender athletic",
        "upright with rounded tips",
        "light copper sickle tail",
        "mature adult",
        "small copper beauty spot beside the right cheek",
        "D-litter red-white family face with Freya's finer build",
        "easy natural stance with a soft direct gaze",
    ),
    "Drift": _v(
        "black",
        "white and pale copper",
        "bold white blaze with pale copper cheek points",
        "one brown and one blue",
        "medium dense",
        "tall athletic",
        "upright and wide-set",
        "black plume with white end",
        "mature adult",
        "white socks rise higher on the front legs",
        "D-litter dark coat balanced by Freya's warm cheek color",
        "alert diagonal stance as if pausing during a walk",
    ),
    "Harbor": _v(
        "steel grey",
        "cream white",
        "broad cream blaze and charcoal eye rims",
        "brown",
        "dense medium",
        "strong long-bodied",
        "upright",
        "dense grey plume",
        "mature adult",
        "dark charcoal patch at the base of the tail",
        "Aurora silver and Fjord agouti blended through the H litter",
        "steady working stance with a calm level head",
    ),
    "Hazel": _v(
        "warm agouti",
        "soft cream",
        "cream spectacles inside a fine dark mask",
        "hazel amber",
        "medium plush",
        "lean balanced",
        "upright with soft tips",
        "agouti plume with cream fringe",
        "mature adult",
        "pale cream diamond on the chest",
        "H-litter agouti structure linking Fjord to the N descendants",
        "composed three-quarter stance with a warm observant expression",
    ),
    "Hugo": _v(
        "silver charcoal",
        "white",
        "symmetrical charcoal cap and white blaze",
        "blue grey",
        "dense medium",
        "broad working",
        "high upright",
        "charcoal plume with white tip",
        "mature adult",
        "thin charcoal line down the white nose",
        "H-litter silver face with Fjord's dense coat",
        "strong square stance with ears sharply attentive",
    ),
    "Hilda": _v(
        "pale agouti",
        "cream white",
        "soft cream face with agouti brow shading",
        "light amber",
        "longer northern",
        "compact balanced",
        "upright and close-set",
        "full pale plume",
        "healthy adult at the time represented",
        "small white star below the throat",
        "H-litter cream-agouti blend and Aurora's open face",
        "gentle relaxed stance with tail naturally lowered",
    ),
    "Halo": _v(
        "pearl grey",
        "white",
        "white face encircled by a thin grey halo mask",
        "one pale blue and one amber",
        "medium plush",
        "slender long-legged",
        "upright and wide-set",
        "pearl plume with a white curl",
        "mature adult",
        "round grey spot high on the left shoulder",
        "light H-litter expression from Aurora with Fjord's eye mask",
        "bright front-facing stance with a curious expression",
    ),
    "Koda": _v(
        "dark sable",
        "cream",
        "cream blaze beneath a dark triangular cap",
        "dark amber",
        "medium dense",
        "powerful lean",
        "upright",
        "sable brush with dark tip",
        "mature adult",
        "copper band across the upper back",
        "C-line silver structure crossed with Django's dark D-line coloring",
        "focused working stance angled slightly toward the camera",
    ),
    "Kira": _v(
        "silver sable",
        "white",
        "delicate white blaze and sable eye points",
        "hazel",
        "medium",
        "athletic balanced",
        "upright with rounded tips",
        "silver-sable plume",
        "mature adult",
        "white crescent on the right shoulder",
        "K-litter blend with Clover's soft face and Django's cap",
        "quiet poised stance with a direct intelligent gaze",
    ),
    "Kenzo": _v(
        "black grey",
        "cream white",
        "cream spectacles and narrow central blaze",
        "brown",
        "short dense",
        "broad-chested",
        "upright and close-set",
        "dark brush with cream underside",
        "mature adult",
        "two cream toe marks on the left forepaw",
        "dark K-litter expression closest to Django, with Clover's grey guard hairs",
        "confident natural stance with head slightly turned",
    ),
    "Kaia": _v(
        "warm sable",
        "ivory",
        "open ivory muzzle and fine sable mask",
        "amber",
        "medium soft",
        "slender",
        "upright with one ear softly angled",
        "warm sable curl with ivory tip",
        "mature adult",
        "small dark teardrop below the right eye",
        "K-litter warmth combining Clover's softness and the D-line copper cast",
        "relaxed side stance with an approachable expression",
    ),
    "Kepler": _v(
        "iron grey",
        "white and tan",
        "white blaze with tan eyebrow points",
        "one blue and one brown",
        "medium dense",
        "tall rangy",
        "large upright",
        "iron-grey plume with white tip",
        "mature adult",
        "thin tan collar marking behind the ears",
        "K-litter grey build with a distinctive D-line tan accent",
        "alert forward stance with a slightly lifted tail",
    ),
    "Kismet": _v(
        "cream sable",
        "white",
        "mostly white face with cream-sable temples",
        "golden brown",
        "longer soft",
        "compact athletic",
        "upright and rounded",
        "full cream plume",
        "healthy adult at the time represented",
        "faint sable patch shaped like a comma on the flank",
        "light K-litter expression inherited from Clover",
        "serene three-quarter stance in soft falling snow",
    ),
    "Maple": _v(
        "maple red",
        "cream white",
        "cream blaze with red cheek panels",
        "amber",
        "medium",
        "lean athletic",
        "upright",
        "red plume with cream fringe",
        "young adult",
        "pale maple leaf-shaped chest patch",
        "Delta's red D-line softened by Coast's pale C-line markings",
        "balanced standing pose with a bright resilient expression",
    ),
    "Magnus": _v(
        "charcoal red sable",
        "white",
        "broad white blaze under a dark sable cap",
        "dark brown",
        "short dense",
        "large powerful",
        "high upright",
        "heavy dark-sable brush",
        "young adult",
        "rust-red band around the lower neck",
        "M-litter cross showing Delta's warmth and Coast's high white blaze",
        "strong square stance with a calm dependable presence",
    ),
    "Mabel": _v(
        "pale copper",
        "white",
        "wide white face with pale copper brow patches",
        "hazel",
        "medium plush",
        "balanced",
        "upright with soft tips",
        "pale copper sickle tail",
        "healthy young adult at the time represented",
        "tiny copper dot centered above the nose",
        "light M-litter expression combining both parents' open faces",
        "gentle side stance with ears relaxed but attentive",
    ),
    "Milo": _v(
        "silver red",
        "cream",
        "cream muzzle and narrow silver-red blaze",
        "amber brown",
        "medium dense",
        "rangy athletic",
        "upright and wide-set",
        "silver-red plume with dark tip",
        "young adult",
        "silver saddle fading into red shoulders",
        "M-litter blend that passes red-grey contrast into the T puppies",
        "alert three-quarter stance with a lively working expression",
    ),
    "Mistral": _v(
        "storm grey",
        "white",
        "windswept asymmetric white blaze",
        "ice blue",
        "medium",
        "slender fast",
        "tall upright",
        "long grey brush with white end",
        "young adult",
        "dark streak sweeping back from the left eye",
        "cool-toned M-litter variation influenced by Coast's silver",
        "dynamic but stationary stance with coat lightly lifted by breeze",
    ),
    "Nova": _v(
        "silver agouti",
        "white",
        "white star blaze inside an agouti mask",
        "one blue and one amber",
        "medium dense",
        "lean athletic",
        "upright",
        "silver-agouti plume",
        "young adult",
        "small white star-shaped chest mark",
        "Hazel's H-line agouti and Koda's dark sable form the N family signature",
        "composed forward stance with an inquisitive direct gaze",
    ),
    "Niko": _v(
        "dark agouti",
        "cream",
        "cream spectacles with a dark forehead wedge",
        "amber",
        "short dense",
        "strong athletic",
        "upright and close-set",
        "dark agouti brush",
        "young adult",
        "thin cream line along the lower jaw",
        "N-litter dark expression with Koda's build and Hazel's eye mask",
        "steady side-facing stance with head turned toward camera",
    ),
    "Nala": _v(
        "warm grey",
        "ivory",
        "ivory butterfly blaze with soft grey cheeks",
        "hazel green",
        "medium soft",
        "slender balanced",
        "upright with rounded tips",
        "warm-grey plume with ivory tip",
        "young adult",
        "small grey patch on the left foreleg",
        "softer N-litter expression closest to Hazel",
        "graceful relaxed stance with a calm open expression",
    ),
    "Nimbus": _v(
        "cloud grey",
        "bright white",
        "broad white blaze beneath a cloud-grey cap",
        "pale blue",
        "longer dense",
        "tall athletic",
        "large upright",
        "full cloud-grey plume",
        "healthy young adult at the time represented",
        "dark silver cloud-shaped saddle",
        "N-litter silver-agouti traits later echoed through the S litter",
        "proud three-quarter stance against a softly misted winter background",
    ),
    "Nora": _v(
        "brown agouti",
        "cream white",
        "cream blaze and fine brown mask",
        "golden amber",
        "medium",
        "lean balanced",
        "upright and slightly wide-set",
        "brown-agouti plume",
        "young adult",
        "cream diagonal slash on the right shoulder",
        "N-litter agouti lineage carried into the V puppies",
        "alert natural stance with a warm attentive expression",
    ),
    "North": _v(
        "black silver",
        "white",
        "sharp white blaze within a black-silver mask",
        "steel blue",
        "short dense",
        "broad athletic",
        "high upright",
        "black-silver brush with white tip",
        "young adult",
        "white compass-point marking on the chest",
        "coolest N-litter expression combining Hazel's mask and Koda's dark coat",
        "focused front three-quarter stance looking into the distance",
    ),
    "Orion": _v(
        "black sable",
        "white and copper",
        "white blaze with copper eyebrow dots",
        "amber brown",
        "medium dense",
        "adolescent athletic",
        "upright and tall",
        "black-sable plume with copper fringe",
        "late-adolescent training dog",
        "three small white stars down the chest",
        "Kira's K-line mask crossed with Magnus's substantial M-line frame",
        "energetic square stance with a youthful alert expression",
    ),
    "Olive": _v(
        "olive agouti",
        "cream",
        "cream spectacles under olive-brown brow shading",
        "hazel",
        "medium",
        "slender adolescent",
        "upright with soft tips",
        "olive-agouti brush",
        "late-adolescent training dog",
        "pale cream oval on the throat",
        "O-litter sable-agouti blend with Kira's fine face",
        "relaxed youthful stance with a slight head tilt",
    ),
    "Otis": _v(
        "dark copper sable",
        "white",
        "white blaze and dark copper cheek panels",
        "dark brown",
        "short dense",
        "broad adolescent",
        "upright",
        "dark copper brush",
        "late-adolescent training dog",
        "black saddle patch ending at mid-back",
        "O-litter warm variation closest to Magnus's red-sable coat",
        "confident youthful stance with forelegs evenly planted",
    ),
    "Opal": _v(
        "pearl silver",
        "white",
        "mostly white face with pearl-silver temples",
        "one pale blue and one hazel",
        "medium plush",
        "balanced adolescent",
        "upright and wide-set",
        "pearl plume",
        "late-adolescent training dog",
        "soft silver ring around the right eye",
        "light O-litter variation echoing Kira's silver ancestry",
        "calm front-facing stance in diffuse winter light",
    ),
    "Onyx": _v(
        "near black",
        "cream white",
        "cream muzzle with a narrow black-split blaze",
        "deep brown",
        "short dense",
        "muscular adolescent",
        "high upright",
        "near-black brush with cream underside",
        "late-adolescent training dog",
        "small white diamond between the shoulders",
        "darkest O-litter expression from both K and M family lines",
        "intense but calm three-quarter stance with ears forward",
    ),
    "Oona": _v(
        "soft sable",
        "ivory",
        "ivory heart blaze and sable cheek shading",
        "amber",
        "medium soft",
        "slender juvenile",
        "upright with rounded tips",
        "soft-sable curl with ivory tip",
        "healthy juvenile at the time represented",
        "small ivory crescent above the left paw",
        "gentle O-litter family face with Kira's softer markings",
        "bright relaxed juvenile stance with a playful expression",
    ),
    "Sanchez": _v(
        "red agouti",
        "cream",
        "cream blaze under a red-agouti cap",
        "amber brown",
        "short dense",
        "lean yearling",
        "upright and large",
        "red-agouti brush",
        "one-year-old junior",
        "dark red stripe centered along the back",
        "S-litter blend of Maple red and Nimbus grey-agouti",
        "alert yearling stance with a confident curious expression",
    ),
    "Sergio": _v(
        "dark cloud grey",
        "white",
        "wide white blaze with dark cloud-grey cheeks",
        "blue grey",
        "medium dense",
        "broad yearling",
        "upright",
        "cloud-grey plume with white tip",
        "healthy near-yearling at the time represented",
        "small white splash on the right shoulder",
        "S-litter grey expression closest to Nimbus",
        "calm near-yearling stance with a steady direct gaze",
    ),
    "Sampo": _v(
        "maple sable",
        "ivory",
        "ivory muzzle and narrow maple-sable blaze",
        "golden amber",
        "medium",
        "compact yearling",
        "upright with rounded tips",
        "maple-sable curl",
        "one-year-old junior",
        "ivory socks with one higher left front sock",
        "S-litter warm expression closest to Maple",
        "friendly yearling stance with head slightly turned",
    ),
    "Sancho": _v(
        "silver sable",
        "cream white",
        "cream spectacles and a silver forehead wedge",
        "one amber and one blue",
        "medium dense",
        "tall yearling",
        "large upright",
        "silver-sable plume",
        "one-year-old junior",
        "thin dark ring around the blue eye",
        "S-litter cross combining Nimbus silver and Maple's warm undercoat",
        "lively but still full-body stance with an attentive gaze",
    ),
    "Siri": _v(
        "light red",
        "white",
        "open white face with delicate red brow arcs",
        "hazel",
        "medium soft",
        "slender yearling",
        "upright and close-set",
        "light-red plume with white tip",
        "one-year-old junior",
        "small red freckle cluster on the muzzle",
        "S-litter light Maple-red expression with Nimbus's fine mask",
        "graceful relaxed yearling stance in soft snow",
    ),
    "Sophie": _v(
        "warm grey",
        "cream",
        "cream butterfly blaze with warm-grey cheeks",
        "amber",
        "medium plush",
        "balanced yearling",
        "upright with soft tips",
        "warm-grey full plume",
        "one-year-old junior",
        "pale cream collar marking",
        "S-litter balanced grey-red family look, paired visually with Sanchez "
        "but not identical",
        "calm approachable stance with a subtle head tilt",
    ),
    "Storm": _v(
        "charcoal agouti",
        "bright white",
        "bold white lightning blaze",
        "ice blue",
        "short dense",
        "rangy yearling",
        "high upright",
        "charcoal brush with white end",
        "one-year-old junior",
        "jagged white chest stripe",
        "S-litter dark Nimbus influence with Maple's high-white chest",
        "alert energetic stance with coat lightly stirred by wind",
    ),
    "Sage": _v(
        "pale sable",
        "ivory",
        "ivory face with pale sable temples",
        "light brown",
        "medium soft",
        "small juvenile",
        "upright with rounded tips",
        "pale-sable curl",
        "healthy nine-month juvenile at the time represented",
        "tiny ivory spot above the nose",
        "softest S-litter expression combining both parents' pale markings",
        "gentle juvenile stance with a curious open expression",
    ),
    "Taro": _v(
        "silver red",
        "white",
        "round white puppy blaze with silver-red ears",
        "amber",
        "fluffy puppy",
        "sturdy young puppy",
        "large upright puppy ears",
        "short fluffy curl",
        "eleven-week-old puppy",
        "red patch over the left shoulder",
        "T-litter combines Nova's silver-agouti mask with Milo's red-grey coat",
        "natural four-paw puppy stance, curious and steady rather than posed "
        "as an adult",
    ),
    "Tessa": _v(
        "soft grey",
        "cream white",
        "cream puppy face with soft grey eye patches",
        "one pale blue and one amber",
        "fluffy puppy",
        "small balanced puppy",
        "upright ears still slightly oversized",
        "soft grey puppy plume",
        "eleven-week-old puppy",
        "white-tipped right ear",
        "T-litter silver face closest to Nova with Milo's warm cream",
        "gentle puppy stance with a small attentive head tilt",
    ),
    "Theo": _v(
        "warm sable",
        "white",
        "broad white blaze beneath sable forehead",
        "brown",
        "short fluffy puppy",
        "broad young puppy",
        "upright rounded puppy ears",
        "short sable brush",
        "eleven-week-old puppy",
        "dark sable spot at the tail base",
        "T-litter warm variation drawing strongly from Milo's M line",
        "confident puppy stance with all paws planted in textured snow",
    ),
    "Tindra": _v(
        "pale silver",
        "snow white",
        "mostly white puppy face with silver temples",
        "blue grey",
        "fluffy puppy",
        "slender young puppy",
        "large upright puppy ears",
        "pale fluffy curl",
        "eleven-week-old puppy",
        "small silver star between the ears",
        "light T-litter expression echoing Nova's blue-eye line",
        "bright curious puppy stance looking directly at camera",
    ),
    "Toast": _v(
        "toasted copper",
        "cream",
        "cream muzzle and toasted-copper cap",
        "dark amber",
        "dense puppy",
        "compact sturdy puppy",
        "upright ears with softly folding tips",
        "short copper plume",
        "eleven-week-old puppy",
        "cream toast-shaped patch on the chest",
        "warmest T-litter expression inherited from Milo and the M line",
        "playful but stationary puppy stance with natural paw placement",
    ),
    "Vega": _v(
        "brown agouti",
        "cream white",
        "tiny cream blaze and brown puppy mask",
        "golden amber",
        "very fluffy puppy",
        "small round young puppy",
        "partly upright young puppy ears",
        "short fluffy agouti tail",
        "six-week-old puppy",
        "cream dot centered on the forehead",
        "V-litter carries Nora's brown-agouti palette and Kenzo's dark mask",
        "very young stable puppy stance with low natural posture and all paws visible",
    ),
    "Valor": _v(
        "black grey",
        "white",
        "wide white puppy blaze inside a black-grey cap",
        "brown",
        "very fluffy puppy",
        "largest sturdy young puppy",
        "one upright and one softly tipped ear",
        "short dark fluffy tail",
        "six-week-old puppy",
        "white shield-shaped chest patch",
        "V-litter dark expression closest to Kenzo with Nora's high white blaze",
        "brave curious young-puppy stance, anatomically natural and not adult-like",
    ),
    "Violet": _v(
        "soft sable grey",
        "ivory",
        "ivory butterfly puppy blaze",
        "one blue and one hazel",
        "very fluffy puppy",
        "small delicate puppy",
        "partly upright rounded ears",
        "short sable-grey curl",
        "six-week-old puppy",
        "faint violet-grey patch around the left eye",
        "V-litter soft cross of Nora's warmth and Kenzo's grey guard hairs",
        "gentle very-young puppy stance with a calm direct look",
    ),
    "Viggo": _v(
        "dark agouti",
        "cream",
        "cream spectacles beneath a dark puppy brow",
        "amber brown",
        "dense fluffy puppy",
        "broad young puppy",
        "upright oversized puppy ears",
        "short dark-agouti brush",
        "six-week-old puppy",
        "thin cream stripe under the chin",
        "V-litter agouti mask joining both N and K ancestry",
        "low sturdy puppy stance with a serious but soft expression",
    ),
    "Viva": _v(
        "pale warm grey",
        "white",
        "open white puppy face with pale-grey temples",
        "light amber",
        "very fluffy puppy",
        "small lively puppy",
        "partly upright soft-tipped ears",
        "short pale-grey plume",
        "six-week-old puppy",
        "tiny grey comma on the right flank",
        "lightest V-litter expression, retaining Nora's open face",
        "lively but still four-square young-puppy stance on believable snow",
    ),
}
